
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key USER-DEFINED NOT NULL UNIQUE,
  name text NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 80),
  description text,
  scope USER-DEFINED NOT NULL,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'active'::role_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT roles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT roles_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid UNIQUE,
  role_id uuid NOT NULL,
  profile_type USER-DEFINED NOT NULL,
  full_name text NOT NULL CHECK (char_length(full_name) >= 2 AND char_length(full_name) <= 140),
  email USER-DEFINED UNIQUE,
  phone text,
  avatar_url text,
  status USER-DEFINED NOT NULL DEFAULT 'invited'::profile_status,
  last_seen_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  role text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'employer'::text, 'guard'::text, 'sub_admin'::text])),
  account_status text NOT NULL DEFAULT 'active'::text,
  mobile text,
  email_verified boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT profiles_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignee_profile_id uuid NOT NULL,
  assigned_by_profile_id uuid,
  entity_table text NOT NULL CHECK (entity_table ~ '^[a-z_]+$'::text),
  entity_id uuid NOT NULL,
  reason text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::admin_assignment_status,
  starts_at timestamp with time zone NOT NULL DEFAULT now(),
  ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT admin_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT admin_assignments_assignee_profile_id_fkey FOREIGN KEY (assignee_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT admin_assignments_assigned_by_profile_id_fkey FOREIGN KEY (assigned_by_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT admin_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT admin_assignments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT admin_assignments_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  legal_name text NOT NULL CHECK (char_length(legal_name) >= 2 AND char_length(legal_name) <= 160),
  display_name text NOT NULL CHECK (char_length(display_name) >= 2 AND char_length(display_name) <= 160),
  slug text NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text),
  registration_number text,
  tax_id text,
  email USER-DEFINED,
  phone text,
  website_url text,
  billing_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'pending_verification'::company_status,
  verified_at timestamp with time zone,
  verified_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT companies_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT companies_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.company_sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text CHECK (char_length(name) >= 2 AND char_length(name) <= 160),
  code text,
  address jsonb NOT NULL DEFAULT '{}'::jsonb,
  latitude numeric,
  longitude numeric,
  contact_name text,
  contact_phone text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::company_site_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  site_name text,
  site_type text,
  city text,
  state text,
  pincode text,
  contact_person text,
  contact_mobile text,
  shift_details text,
  notes text,
  employer_user_id uuid,
  CONSTRAINT company_sites_pkey PRIMARY KEY (id),
  CONSTRAINT company_sites_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT company_sites_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT company_sites_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id),
  CONSTRAINT company_sites_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT company_sites_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id)
);
CREATE TABLE public.employers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  company_id uuid NOT NULL,
  designation text,
  department text,
  work_email USER-DEFINED,
  work_phone text,
  can_manage_jobs boolean NOT NULL DEFAULT true,
  can_manage_payments boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'pending_verification'::employer_status,
  verified_at timestamp with time zone,
  verified_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT employers_pkey PRIMARY KEY (id),
  CONSTRAINT employers_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT employers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT employers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT employers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT employers_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT employers_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.guards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  guard_code text NOT NULL UNIQUE,
  date_of_birth date,
  gender text,
  skills ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  experience_months integer NOT NULL DEFAULT 0 CHECK (experience_months >= 0),
  expected_monthly_rate_cents bigint CHECK (expected_monthly_rate_cents >= 0),
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  current_company_site_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending_verification'::guard_status,
  verified_at timestamp with time zone,
  verified_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT guards_pkey PRIMARY KEY (id),
  CONSTRAINT guards_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT guards_current_company_site_id_fkey FOREIGN KEY (current_company_site_id) REFERENCES public.company_sites(id),
  CONSTRAINT guards_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT guards_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT guards_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT guards_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_type USER-DEFINED NOT NULL,
  owner_id uuid NOT NULL,
  document_type USER-DEFINED NOT NULL,
  title text NOT NULL CHECK (char_length(title) >= 2 AND char_length(title) <= 160),
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  file_size_bytes bigint CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::document_status,
  uploaded_by uuid,
  verified_at timestamp with time zone,
  verified_by uuid,
  rejected_reason text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  company_site_id uuid,
  employer_id uuid,
  title text NOT NULL CHECK (char_length(title) >= 2 AND char_length(title) <= 160),
  description text,
  required_guards integer NOT NULL DEFAULT 1 CHECK (required_guards > 0),
  start_date date,
  end_date date,
  shift_start time without time zone,
  shift_end time without time zone,
  pay_rate_cents bigint CHECK (pay_rate_cents IS NULL OR pay_rate_cents >= 0),
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::job_status,
  published_at timestamp with time zone,
  closed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT jobs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_company_site_id_fkey FOREIGN KEY (company_site_id) REFERENCES public.company_sites(id),
  CONSTRAINT jobs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT jobs_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  guard_id uuid NOT NULL,
  cover_note text,
  status USER-DEFINED NOT NULL DEFAULT 'applied'::job_application_status,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  guard_user_id uuid,
  employer_user_id uuid,
  company_id uuid,
  site_id uuid,
  notes text,
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_applications_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT job_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT job_applications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT job_applications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT job_applications_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hiring_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_application_id uuid NOT NULL,
  stage USER-DEFINED NOT NULL DEFAULT 'applied'::hiring_stage,
  stage_order integer NOT NULL DEFAULT 1 CHECK (stage_order > 0),
  assigned_to uuid,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::hiring_workflow_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT hiring_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT hiring_workflows_job_application_id_fkey FOREIGN KEY (job_application_id) REFERENCES public.job_applications(id),
  CONSTRAINT hiring_workflows_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT hiring_workflows_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT hiring_workflows_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT hiring_workflows_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.attendance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guard_id uuid NOT NULL,
  job_id uuid,
  company_site_id uuid,
  event_type USER-DEFINED NOT NULL,
  event_at timestamp with time zone NOT NULL DEFAULT now(),
  work_date date NOT NULL DEFAULT CURRENT_DATE,
  latitude numeric,
  longitude numeric,
  notes text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::attendance_status,
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT attendance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_logs_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT attendance_logs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT attendance_logs_company_site_id_fkey FOREIGN KEY (company_site_id) REFERENCES public.company_sites(id),
  CONSTRAINT attendance_logs_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT attendance_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT attendance_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.agreements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  employer_id uuid,
  guard_id uuid,
  job_id uuid,
  agreement_number text NOT NULL UNIQUE,
  title text NOT NULL CHECK (char_length(title) >= 2 AND char_length(title) <= 160),
  terms jsonb NOT NULL DEFAULT '{}'::jsonb,
  effective_from date,
  effective_until date,
  signed_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::agreement_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  offer_id uuid,
  guard_user_id uuid,
  employer_user_id uuid,
  site_id uuid,
  employer_confirmation_status text NOT NULL DEFAULT 'pending'::text,
  guard_confirmation_status text NOT NULL DEFAULT 'pending'::text,
  platform_confirmation_status text NOT NULL DEFAULT 'pending'::text,
  CONSTRAINT agreements_pkey PRIMARY KEY (id),
  CONSTRAINT agreements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT agreements_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT agreements_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT agreements_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT agreements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT agreements_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT agreements_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_type USER-DEFINED NOT NULL,
  profile_id uuid,
  company_id uuid,
  employer_id uuid,
  guard_id uuid,
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  available_balance_cents bigint NOT NULL DEFAULT 0,
  pending_balance_cents bigint NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'active'::wallet_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT wallets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT wallets_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT wallets_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT wallets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT wallets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT wallets_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  transaction_type USER-DEFINED NOT NULL,
  amount_cents bigint NOT NULL CHECK (amount_cents > 0),
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  balance_after_cents bigint,
  reference_type text,
  reference_id uuid,
  external_reference text,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::wallet_transaction_status,
  posted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  employer_user_id uuid,
  amount numeric NOT NULL DEFAULT 0,
  purpose text,
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id),
  CONSTRAINT wallet_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT wallet_transactions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_type USER-DEFINED NOT NULL,
  payer_profile_id uuid,
  payee_profile_id uuid,
  company_id uuid,
  employer_id uuid,
  guard_id uuid,
  payer_wallet_id uuid,
  payee_wallet_id uuid,
  amount_cents bigint NOT NULL CHECK (amount_cents > 0),
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  provider text,
  provider_reference text,
  status USER-DEFINED NOT NULL DEFAULT 'initiated'::payment_status,
  due_at timestamp with time zone,
  paid_at timestamp with time zone,
  failed_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  guard_user_id uuid,
  employer_user_id uuid,
  job_id uuid,
  application_id uuid,
  amount numeric NOT NULL DEFAULT 0,
  payment_method text,
  payment_status text NOT NULL DEFAULT 'pending'::text,
  payment_date timestamp with time zone,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_payer_profile_id_fkey FOREIGN KEY (payer_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_payee_profile_id_fkey FOREIGN KEY (payee_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT payments_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT payments_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT payments_payer_wallet_id_fkey FOREIGN KEY (payer_wallet_id) REFERENCES public.wallets(id),
  CONSTRAINT payments_payee_wallet_id_fkey FOREIGN KEY (payee_wallet_id) REFERENCES public.wallets(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT payments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.commissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid,
  company_id uuid,
  employer_id uuid,
  guard_id uuid,
  commission_rate_bps integer CHECK (commission_rate_bps IS NULL OR commission_rate_bps >= 0 AND commission_rate_bps <= 10000),
  amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
  currency character NOT NULL DEFAULT 'INR'::bpchar,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::commission_status,
  earned_at timestamp with time zone,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT commissions_pkey PRIMARY KEY (id),
  CONSTRAINT commissions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT commissions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT commissions_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT commissions_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT commissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT commissions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_profile_id uuid NOT NULL,
  actor_profile_id uuid,
  channel USER-DEFINED NOT NULL DEFAULT 'in_app'::notification_channel,
  title text NOT NULL CHECK (char_length(title) >= 2 AND char_length(title) <= 160),
  body text NOT NULL,
  action_url text,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::notification_status,
  sent_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  user_id uuid,
  message text,
  type text NOT NULL DEFAULT 'info'::text,
  is_read boolean NOT NULL DEFAULT false,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_profile_id_fkey FOREIGN KEY (recipient_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_actor_profile_id_fkey FOREIGN KEY (actor_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT notifications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT notifications_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_number text NOT NULL UNIQUE,
  requester_profile_id uuid NOT NULL,
  assigned_to_profile_id uuid,
  company_id uuid,
  employer_id uuid,
  guard_id uuid,
  subject text NOT NULL CHECK (char_length(subject) >= 2 AND char_length(subject) <= 180),
  description text NOT NULL,
  priority USER-DEFINED NOT NULL DEFAULT 'normal'::support_ticket_priority,
  status USER-DEFINED NOT NULL DEFAULT 'open'::support_ticket_status,
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  user_id uuid,
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_requester_profile_id_fkey FOREIGN KEY (requester_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_assigned_to_profile_id_fkey FOREIGN KEY (assigned_to_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT support_tickets_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT support_tickets_guard_id_fkey FOREIGN KEY (guard_id) REFERENCES public.guards(id),
  CONSTRAINT support_tickets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT support_tickets_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.admin_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_profile_id uuid,
  action text NOT NULL CHECK (char_length(action) >= 2 AND char_length(action) <= 120),
  entity_table text NOT NULL CHECK (char_length(entity_table) >= 2 AND char_length(entity_table) <= 120),
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  request_id text,
  ip_address inet,
  user_agent text,
  status USER-DEFINED NOT NULL DEFAULT 'recorded'::log_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT admin_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_activity_logs_actor_profile_id_fkey FOREIGN KEY (actor_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT admin_activity_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT admin_activity_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.verification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  subject_profile_id uuid,
  document_id uuid,
  verifier_profile_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::verification_status,
  notes text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT verification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT verification_logs_subject_profile_id_fkey FOREIGN KEY (subject_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT verification_logs_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT verification_logs_verifier_profile_id_fkey FOREIGN KEY (verifier_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT verification_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT verification_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.app_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL CHECK (setting_key ~ '^[a-z0-9_.-]+$'::text),
  scope USER-DEFINED NOT NULL DEFAULT 'global'::app_setting_scope,
  company_id uuid,
  company_site_id uuid,
  profile_id uuid,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_secret boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'active'::app_setting_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT app_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT app_settings_company_site_id_fkey FOREIGN KEY (company_site_id) REFERENCES public.company_sites(id),
  CONSTRAINT app_settings_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT app_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT app_settings_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.employer_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  contact_person_name text,
  designation text,
  city text,
  state text,
  pincode text,
  is_aadhaar_verified boolean NOT NULL DEFAULT false,
  aadhaar_verification_status text NOT NULL DEFAULT 'pending'::text,
  aadhaar_verified_at timestamp with time zone,
  aadhaar_last_four text,
  profile_status text NOT NULL DEFAULT 'incomplete'::text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  admin_remarks text,
  rejection_reason text,
  created_from text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT employer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT employer_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.employer_aadhaar_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_user_id uuid NOT NULL,
  aadhaar_number_hash text,
  aadhaar_last_four text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  otp_sent_to text,
  otp_channel text NOT NULL DEFAULT 'email'::text,
  otp_expires_at timestamp with time zone,
  otp_verified_at timestamp with time zone,
  otp_attempts integer NOT NULL DEFAULT 0,
  resend_count integer NOT NULL DEFAULT 0,
  provider_name text NOT NULL DEFAULT 'email_otp'::text,
  verification_response jsonb,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employer_aadhaar_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT employer_aadhaar_verifications_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.employer_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_user_id uuid NOT NULL,
  company_name text NOT NULL,
  business_type text,
  registration_type text,
  gst_number text,
  pan_number text,
  company_email text,
  company_phone text,
  website text,
  logo_url text,
  description text,
  registered_address text,
  billing_address text,
  city text,
  state text,
  pincode text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  account_status text NOT NULL DEFAULT 'active'::text,
  admin_remarks text,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employer_companies_pkey PRIMARY KEY (id),
  CONSTRAINT employer_companies_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.company_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employer_user_id uuid NOT NULL,
  document_type text,
  file_path text NOT NULL,
  file_url text,
  file_size bigint,
  file_type text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  admin_remarks text,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT company_documents_pkey PRIMARY KEY (id),
  CONSTRAINT company_documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id),
  CONSTRAINT company_documents_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_user_id uuid NOT NULL,
  company_id uuid,
  site_id uuid,
  title text NOT NULL,
  category text,
  guard_type text,
  guards_required integer NOT NULL DEFAULT 1,
  gender_preference text NOT NULL DEFAULT 'Any'::text,
  experience_required text,
  salary_amount numeric,
  payment_type text,
  duty_hours text,
  shift_type text,
  start_date date,
  end_date date,
  duration_type text,
  required_skills ARRAY,
  language_requirements ARRAY,
  police_verification_required boolean NOT NULL DEFAULT false,
  uniform_required boolean NOT NULL DEFAULT false,
  food_facility boolean NOT NULL DEFAULT false,
  accommodation_facility boolean NOT NULL DEFAULT false,
  description text,
  special_instructions text,
  status text NOT NULL DEFAULT 'draft'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  latitude numeric,
  longitude numeric,
  CONSTRAINT job_posts_pkey PRIMARY KEY (id),
  CONSTRAINT job_posts_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT job_posts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id),
  CONSTRAINT job_posts_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.company_sites(id)
);
CREATE TABLE public.attendance_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  guard_user_id uuid NOT NULL,
  employer_user_id uuid,
  company_id uuid,
  job_id uuid,
  site_id uuid,
  attendance_date date NOT NULL,
  in_time timestamp with time zone,
  out_time timestamp with time zone,
  total_hours numeric,
  status text NOT NULL DEFAULT 'pending_verification'::text,
  employer_remarks text,
  guard_remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_records_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_records_guard_user_id_fkey FOREIGN KEY (guard_user_id) REFERENCES auth.users(id),
  CONSTRAINT attendance_records_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT attendance_records_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id),
  CONSTRAINT attendance_records_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posts(id),
  CONSTRAINT attendance_records_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.company_sites(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_user_id uuid NOT NULL,
  company_id uuid,
  invoice_number text,
  amount numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'pending'::text,
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  paid_at timestamp with time zone,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id)
);
CREATE TABLE public.employer_wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_user_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employer_wallets_pkey PRIMARY KEY (id),
  CONSTRAINT employer_wallets_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.interview_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid,
  job_id uuid,
  guard_user_id uuid NOT NULL,
  employer_user_id uuid,
  company_id uuid,
  request_type text NOT NULL DEFAULT 'Phone Call'::text,
  preferred_date date,
  preferred_time time without time zone,
  message text,
  status text NOT NULL DEFAULT 'requested'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interview_requests_pkey PRIMARY KEY (id),
  CONSTRAINT interview_requests_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.job_applications(id),
  CONSTRAINT interview_requests_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posts(id),
  CONSTRAINT interview_requests_guard_user_id_fkey FOREIGN KEY (guard_user_id) REFERENCES auth.users(id),
  CONSTRAINT interview_requests_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT interview_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id)
);
CREATE TABLE public.job_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid,
  job_id uuid,
  guard_user_id uuid NOT NULL,
  employer_user_id uuid,
  company_id uuid,
  site_id uuid,
  offered_salary numeric,
  duty_hours text,
  shift_type text,
  start_date date,
  terms_summary text,
  status text NOT NULL DEFAULT 'sent'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_offers_pkey PRIMARY KEY (id),
  CONSTRAINT job_offers_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.job_applications(id),
  CONSTRAINT job_offers_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posts(id),
  CONSTRAINT job_offers_guard_user_id_fkey FOREIGN KEY (guard_user_id) REFERENCES auth.users(id),
  CONSTRAINT job_offers_employer_user_id_fkey FOREIGN KEY (employer_user_id) REFERENCES auth.users(id),
  CONSTRAINT job_offers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.employer_companies(id),
  CONSTRAINT job_offers_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.company_sites(id)
);
CREATE TABLE public.guard_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  full_name text,
  mobile text,
  gender text,
  dob date,
  address text,
  city text,
  state text,
  pincode text,
  latitude numeric,
  longitude numeric,
  skills ARRAY,
  languages ARRAY,
  experience text,
  aadhaar_status text NOT NULL DEFAULT 'pending'::text,
  police_verification_status text NOT NULL DEFAULT 'pending'::text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  bank_account_number text,
  bank_ifsc text,
  bank_name text,
  account_holder_name text,
  avatar_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT guard_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT guard_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);